set-window-option -g mode-keys vi
set -g default-terminal "screen-256color"
set -g prefix C-a


unbind C-b
bind C-a send-prefix

unbind %
bind | split-window -h

set -g base-index 1
set -g pane-base-index 1


unbind '"'
bind - split-window -v
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r h select-pane -L

bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r H resize-pane -L 5

unbind Left
unbind Down
unbind Up
unbind Right

set -g mouse on
set -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'thuantanphamfilms/tmux-fzf-session-switch'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @ressurect-save-panes-content 'on'
set -g @continuum-restore 'on'
set -g @ressurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @yank-selection 'clipboard'

set -g @catppuccin_date_time_text "%H:%M"
set -g @fzf-goto-session 'f'

# Show status bar
set -g status on

# Left-align everything
set -g status-justify left

# Remove all left/right content
set -g status-left ""
set -g status-right "#[fg=green]#{session_name} "

set-option -g status-style bg=default

# Format windows to show just index
setw -g window-status-format "#{window_index} "
setw -g window-status-current-format "[#{window_index}] "

# sets status bar of tmux to top
set-option -g @fzf-goto-session-only 'true'


run '~/.tmux/plugins/tpm/tpm'
